--function init_tracing(game)
--  local circle =
--    imap(function (a) return v2.unit(a*math.pi/6) end, range(0, 11))
--  function game.trace_circle(source, pos, radius)
--    if not game.is_key_down(('D'):byte()) then
--      return
--    end
--    local self = {}
--    function self.trace_cleanup()
--      self.is_dead = true
--    end
--    function self.draw_debug()
--      if source then
--        glColor4d(1, 1, 1, 1/4)
--        glBegin(GL_LINES)
--        glVertex2d(source.x, source.y)
--        glVertex2d(pos.x, pos.y)
--        glEnd()
--      end
--      glColor4d(1, 1, 1, 1/2)
--      glBegin(GL_LINE_LOOP)
--      for _, v in ipairs(circle) do
--        glVertex2d(pos.x + v.x * radius, pos.y + v.y * radius)
--      end
--      glEnd()
--      glColor3d(1, 1, 1)
--    end
--    game.add_actor(self)
--  end
--end
